version: "2.2"
services:
  frontend:
    build: ./services/frontend/dockerfile.dev
    stdin_open: true
    depends_on:
      - api
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./services/frontend:/srv
      - ./.docker/frontend/.cache:/home/node/.cache
  api:
    build: ./services/api/dockerfile.dev
    stdin_open: true
    command: ["yarn", "start:dev"]
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./services/api:/srv
  redis:
    image: redis:5-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2m
      retries: 5
    ports:
      - 6379:6379
