apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: journal
build:
  artifacts:
    - image: gcr.io/general-270806/jounal-frontend
      context: services/frontend
      docker:
        dockerfile: dockerfile
    - image: gcr.io/general-270806/jounal-api
      context: services/api
      docker:
        dockerfile: dockerfile
deploy:
  helm:
    releases:
      - name: journal
        chartPath: .helm
        artifactOverrides:
          api:
            image: gcr.io/general-270806/jounal-api
          frontend:
            image: gcr.io/general-270806/jounal-frontend
