apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{.Chart.Name}}-frontend"
  name: "{{.Chart.Name}}-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{.Chart.Name}}-frontend"
  template:
    metadata:
      labels:
        app: "{{.Chart.Name}}-frontend"
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: "{{.Chart.Name}}-frontend"
          image: {{.Values.frontend.image}}
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{.Chart.Name}}-frontend-config"
                  key: apiEndpoint
          ports:
            - containerPort: {{ .Values.frontend.port }}
