apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{.Chart.Name}}-frontend"
  name: "{{.Chart.Name}}-frontend"
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      protocol: TCP
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: "{{.Chart.Name}}-frontend"
  type: NodePort
