apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: gcr.io/aqueous-timer-291305/journal-api:1.0.1
          command:
            - yarn
            - start
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: apiPort
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: redisHost
          ports:
            - containerPort: 4000
          name: api
          # Setting Request equal to Limit will lead to the most predictable
          # behavior of your application.
          resources:
            requests:
              cpu: "0.25"
              memory: "0.2G"
            limits:
              cpu: "0.25"
              memory: "0.2G"
