apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{.Chart.Name}}-redis"
  name: "{{.Chart.Name}}-redis"
spec:
  ports:
    - port: {{.Values.redis.port}}
      protocol: TCP
      targetPort: {{.Values.redis.port}}
  selector:
    app: "{{.Chart.Name}}-redis"
  sessionAffinity: None
  type: NodePort
