apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "journal.fullname" . }}-redis
  name: {{ template "journal.fullname" . }}-redis
  namespace: default
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: {{ template "journal.fullname" . }}-redis
  sessionAffinity: None
  type: NodePort
