apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{.Chart.Name}}-redis"
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: "{{.Chart.Name}}-redis"
  template:
    metadata:
      labels:
        app: "{{.Chart.Name}}-redis"
    spec:
      containers:
        - name: "{{.Chart.Name}}-redis"
          image: {{.Values.redis.image}}
          ports:
            - containerPort: {{.Values.redis.port}}
              name: redis
          volumeMounts:
            - mountPath: /data
              name: "{{.Chart.Name}}-redis-data"
  volumeClaimTemplates:
    - metadata:
        name: "{{.Chart.Name}}-redis-data"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "10Gi"
