apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{.Chart.Name}}-api"
  name: "{{.Chart.Name}}-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{.Chart.Name}}-api"
  template:
    metadata:
      labels:
        app: "{{.Chart.Name}}-api"
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: {{.Values.api.image}}
          command:
            - yarn
            - start
          imagePullPolicy: Always
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: "{{.Chart.Name}}-api-config"
                  key: apiPort
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: "{{.Chart.Name}}-api-config"
                  key: redisHost
          ports:
            - containerPort: 4000
          name: "{{.Chart.Name}}-api"
          # Setting Request equal to Limit will lead to the most predictable
          # behavior of your application.
          resources:
            requests:
              cpu: "0.25"
              memory: "0.2G"
            limits:
              cpu: "0.25"
              memory: "0.2G"
