apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "journal.fullname" . }}-api
  name: {{ template "journal.fullname" . }}-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "journal.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ template "journal.fullname" . }}-api
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: "gcr.io/aqueous-timer-291305/journal-api:{{ .Chart.AppVersion }}"
          command:
            - yarn
            - start
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "journal.fullname" . }}-api-config
                  key: apiPort
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "journal.fullname" . }}-api-config
                  key: redisHost
          ports:
            - containerPort: 4000
          name: {{ template "journal.fullname" . }}-api
          # Setting Request equal to Limit will lead to the most predictable
          # behavior of your application.
          resources:
            requests:
              cpu: "0.25"
              memory: "0.2G"
            limits:
              cpu: "0.25"
              memory: "0.2G"
