apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "journal.fullname" . }}-api
  name: {{ template "journal.fullname" . }}-api
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: {{ template "journal.fullname" . }}-api
  type: NodePort
