apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{.Chart.Name}}-api"
  name: "{{.Chart.Name}}-api"
spec:
  ports:
    - port: {{.Values.api.port}}
      protocol: TCP
      targetPort: {{.Values.api.port}}
  selector:
    app: "{{.Chart.Name}}-api"
  type: NodePort
