apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{.Chart.Name}}-ingress"
spec:
  rules:
      - host: "api.journal.example"
        http:
          paths:
            - path: /*
              backend:
                serviceName: "{{.Chart.Name}}-api"
                servicePort: {{.Values.api.port}}
      - host: "journal.example"
        http:
          paths:
            - path: /*
              backend:
                serviceName: "{{.Chart.Name}}-frontend"
                servicePort: {{.Values.frontend.port}}
