apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "journal.fullname" . }}-ingress
spec:
  rules:
      - host: "api.journal.example"
        http:
          paths:
            - path: /*
              backend:
                serviceName: {{ template "journal.fullname" . }}-api
                servicePort: 4000
      - host: "journal.example"
        http:
          paths:
            - path: /*
              backend:
                serviceName: {{ template "journal.fullname" . }}-frontend
                servicePort: 3000
