apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: files
  name: files
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
        - name: files
          image: nginx:alpine
          imagePullPolicy: Always
          terminationMessagePath: /dev/terminatation-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.25"
              memory: "0.2G"
            limits:
              cpu: "0.25"
              memory: "0.2G"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
