apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: frontend
          image: gcr.io/aqueous-timer-291305/journal-frontend:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: apiEndpoint
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.25"
              memory: "0.2G"
            limits:
              cpu: "0.25"
              memory: "0.2G"
