apiVersion: v1
kind: Service
metadata:
  labels:
    app: files
  name: files
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: files
  sessionAffinity: None
  type: NodePort
