FROM node:12-alpine
COPY . /srv
WORKDIR /srv/build
ENV PATH /srv/node_modules/.bin:$PATH
ENV REACT_APP_API_ENDPOINT http://api.journal.example
RUN cd /srv && yarn install && yarn build
RUN yarn global add serve
EXPOSE 3000
CMD serve -s -l 3000
